---
- name: Gather OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ pkgs }}"
