---
- name: Add Jenkins apt repository key
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Download specific Jenkins version if needed
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
    dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  when: jenkins_version is defined

- name: Install specific version of Jenkins if needed
  apt:
    deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
    state: installed
  when: jenkins_version is defined
  notify: configure default users

- name: Otherwise install Jenkins
  apt:
    name: jenkins
    state: "{{ jenkins_package_state }}"

- name: Configure default users
  template:
    src: basic-security.groovy
    dest: "{{ jenkins_basic_security_path }}"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
